language: node_js
os: linux
dist: xenial
branches:
  only:
  - master
node_js:
- lts/*
cache:
  directories:
    - "$HOME/.npm"
jobs:
  include:
    - name: warmup
      stage: warmup
      script:
        - npm ci
    - name: test
      stage: test
      services:
        - redis
      install:
        - npm ci
      before_script:
        - NODE_ENV=test npx sequelize-cli db:migrate
      script:
        - npm run lint-ci
        - npm test
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - name: test build
      stage: test
      install:
        - npm ci
      script: npm run build
    - name: build docker image
      stage: upload
      if: branch = master
      services:
        - docker
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "dyc3" --password-stdin
      script:
        - docker-compose -f docker/docker-compose.yml up -d --build
        - docker commit opentogethertube opentogethertube
        - docker-compose -f docker/docker-compose.yml down
        - docker tag opentogethertube dyc3/opentogethertube:latest
        - docker push dyc3/opentogethertube:latest
