[default]
locale = "en-us"

[default.extend-words]
guage = "gauge"
AVOD = "AVOD"
ser = "ser"
seeked = "seeked"
# google drive misspelled this in their API
aknowledge = "aknowledge"
# Odysee
odysee = "odysee"
ody = "Ody"

[files]
extend-exclude = [
	"server/tests/unit/fixtures",
	"server/tests/unit/services/youtube.spec.ts",
	"client/src/locales",
	"!client/src/locales/en.ts",
	"deploy/nginx.prod.conf",
]
