app = "ott-balancer-staging"
primary_region = "ewr"

[build]
dockerfile = "balancer.Dockerfile"

[build.args]
DEPLOY_TARGET = "ott-balancer-staging"

[deploy]
strategy = "canary"

[http_service]
internal_port = 8081
force_https = true
# auto_stop_machines = true
# auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "10s"
path = "/api/status"

[metrics]
port = 8081
path = "/api/status/metrics"
